/*
 * File: app/store/distanceStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.distanceStore', {
    extend: 'Ext.data.Store',
    alias: 'store.distanceStore',

    requires: [
        'MyApp.model.DistanceModel'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        data: [
            {
                name: '60 feet',
                value: 60
            },
            {
                name: '150 feet',
                value: 150
            },
            {
                name: '300 feet',
                value: 300
            },
            {
                name: '500 feet',
                value: 500
            }
        ],
        model: 'MyApp.model.DistanceModel',
        storeId: 'distanceStore'
    }
});