/*
 * File: app/store/mycouponsStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.mycouponsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.PrintedCoupon'
    ],

    config: {
        autoLoad: false,
        autoSync: false,
        model: 'MyApp.model.PrintedCoupon',
        storeId: 'mycouponsStore',
        proxy: {
            type: 'jsonp',
            url: 'http://190.241.119.228/getPrintedCouponsJsonP',
            reader: {
                type: 'json',
                rootProperty: 'result'
            }
        },
        sorters: {
            property: 'name'
        },
        grouper: {
            groupFn: function(record) {
                return record.get("name")[0];
            }
        }
    }
});