/*
 * File: app/view/couponPopUp.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.couponPopUp', {
    extend: 'Ext.Panel',
    alias: 'widget.couponPopUp',

    config: {
        left: 0,
        top: '12%',
        width: '95%',
        cls: [
            'couponPopUp'
        ],
        showAnimation: {
            type: 'pop'
        },
        tpl: [
            '<img class="anchorCoupon" src="assets/icons/anchorCoupon.png"/>',
            '',
            '<div class=\'descripcionContainerPopUp\'>',
            '    <div class=\'imageContainerPopUp\'><img src="{image}"/></div>',
            '    <p class=\'titleListPopUp\'>{name}</p>',
            '    <p class=\'descriptionListPopUp\'>{shortDiscount}...</p>',
            '</div>    '
        ],
        items: [
            {
                xtype: 'container',
                cls: [
                    'btnContainerPopUp'
                ],
                items: [
                    {
                        xtype: 'button',
                        cls: 'generalBtn detailCouponBtn popUpButton',
                        itemId: 'mybutton3',
                        ui: 'action-round',
                        icon: 'assets/icons/redeemIcon.png',
                        iconCls: 'detailPopUpIcon',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        cls: 'generalBtn detailCouponBtn popUpButton',
                        itemId: 'okBtn',
                        ui: 'action-round',
                        icon: 'assets/icons/okIcon.png',
                        iconCls: 'detailPopUpIcon',
                        text: ''
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybutton3Tap',
                event: 'tap',
                delegate: '#mybutton3'
            },
            {
                fn: 'onMybutton4Tap',
                event: 'tap',
                delegate: '#okBtn'
            },
            {
                fn: 'onPanelShow',
                event: 'show'
            }
        ]
    },

    onMybutton3Tap: function(button, e, options) {
        this.consume = true;

        var appContainer = Ext.getCmp("appContainer");

        var idCupon = this.getData().couponID;

        MyApp.removePopUpFromScreen(idCupon);

        MyApp.maskComponent(appContainer,"loading...");

        MyApp.printCoupon(idCupon,function(result,printedCoupon){

            MyApp.unMaskComponent(appContainer);    

            if(result == 1){
                var store = Ext.getStore("couponList");

                var record = store.getAt(store.find("couponID",idCupon));

                if(record !== undefined){
                    store.remove(record); 
                }

                //Ext.Msg.alert('Added!!', "The coupon has been added to your List of coupons", Ext.emptyFn);
                //alert("The coupon has been added to your List of coupons");

                if(navigator.notification.alert !== null){

                    navigator.notification.alert('The coupon has been added to your List of coupons',  function(){console.log("ok");},'Added!!','Continue'); 
                }else{
                    alert("The coupon has been added to your List of coupons"); 
                }
            }

        });
        this.hideAndDestroy();

    },

    onMybutton4Tap: function(button, e, options) {
        this.addToCouponList(this);

    },

    onPanelShow: function(component, options) {
        this.consume = false;

        window.setTimeout(function(){
            component.addToCouponList(component);
        }, 8000);
    },

    addToCouponList: function(component) {

        var idCupon = this.getData().couponID;

        MyApp.removePopUpFromScreen(idCupon);

        if(!this.consume){
            var merchants = Ext.getStore("closestMerchants");
            var merchant = merchants.getAt(merchants.find("id",this.getData().merchant_id));

            if(merchant === undefined){
                var totalMerchants = Ext.getStore("getMerchants");
                merchant = totalMerchants.getAt(totalMerchants.find("id",this.getData().merchant_id));
            }

            var merchantCoupons = merchant.coupons(); 
            var coupon = merchantCoupons.getAt(merchantCoupons.find("id",this.getData().id));
            var couponList = Ext.getStore("couponList");

            var couponTmp = couponList.find("couponID",coupon.get("couponID"));

            if(couponTmp == -1){
                couponList.add(coupon);
            }


            this.hideAndDestroy(); 

            this.consume = true;
        }


    },

    hideAndDestroy: function() {
        this.hide();

        var appContainer = Ext.getCmp('appContainer');

        if(appContainer !== null){
            appContainer.remove(this);
        }



        this.destroy();
    }

});