/*
 * File: app/view/couponDetailView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.couponDetailView', {
    extend: 'Ext.Panel',
    alias: 'widget.couponDetailView',

    config: {
        centered: true,
        height: '100%',
        id: 'couponDetailView',
        itemId: 'couponDetailView',
        left: 0,
        styleHtmlContent: true,
        top: 0,
        width: '100%',
        layout: {
            type: 'vbox'
        },
        modal: true,
        scrollable: false,
        cls: [
            'generalModal'
        ],
        hideAnimation: {
            type: 'slideOut',
            direction: 'right'
        },
        showAnimation: {
            type: 'slide'
        },
        tpl: [
            '<div class="globalContainer">',
            '    <div class="couponContainer">',
            '        <img class="imageTijeras" src="assets/icons/tijeras.png"/>',
            '        <div class="titleContainer">',
            '            <div class=\'imageContainerCoupon\'>',
            '                <img src="{image}"/>',
            '            </div>',
            '            <div class="titleTextContainer">',
            '                <p class="titleName">{name}</p>',
            '                <p class="descripcionTitle">Address <span>{address}</span></p>',
            '                <div class="addressContainer">',
            '                    <p class="descripcionTitle cityText">City <span>{city}</span></p>',
            '                    <p class="descripcionTitle stateText">State <span>{state}</span></p>  ',
            '                </div>                ',
            '                <p class="descripcionTitle">Phone <span>{phone}</span></p>',
            '                <p class="descripcionTitle">ZIP Code <span>{zipCode}</span></p>',
            '            </div>',
            '        </div>    ',
            '        <div class="discountContainer">         ',
            '            <p>{discount}</p>               ',
            '        </div>                     ',
            '        ',
            '        <div class="terms">',
            '            <p>Terms: <span>{terms}</span></p>',
            '        </div>      ',
            '        ',
            '    </div>',
            '</div>',
            '',
            ''
        ],
        items: [
            {
                xtype: 'toolbar',
                cls: [
                    'commonToolbar'
                ],
                docked: 'top',
                id: 'detailToolbar',
                title: '',
                items: [
                    {
                        xtype: 'button',
                        cls: 'generalBtn backBtn',
                        id: 'backDetailBtnCoupon',
                        itemId: 'mybutton10',
                        ui: 'action-round',
                        icon: 'assets/icons/backIcon.png',
                        iconCls: 'backIcon'
                    },
                    {
                        xtype: 'image',
                        flex: 1,
                        cls: [
                            'commonToolbarIcon',
                            'commonToolbarIconWithBack'
                        ],
                        id: 'detailToolbar',
                        styleHtmlContent: true,
                        src: 'assets/general/commonToolbarIcon.png'
                    }
                ]
            },
            {
                xtype: 'container',
                bottom: 0,
                height: '75px',
                id: 'btnContainer',
                itemId: 'btnContainer',
                left: '54%',
                style: 'position : absolute;',
                width: '80%',
                items: [
                    {
                        xtype: 'container',
                        id: 'btnContainerRelative',
                        itemId: 'btnContainerRelative',
                        left: '-50%',
                        style: 'position : relative;',
                        width: '100%',
                        items: [
                            {
                                xtype: 'button',
                                cls: 'generalBtn detailCouponBtn',
                                height: '70px',
                                id: 'redeemBtnDetail',
                                itemId: 'mybutton17',
                                style: 'float : left; margin-right : 5%;margin-left : 5%',
                                ui: 'action-round',
                                width: '60px',
                                icon: 'assets/icons/redeemIcon.png',
                                iconCls: 'detailPopUpIcon',
                                text: ''
                            },
                            {
                                xtype: 'button',
                                cls: 'generalBtn detailCouponBtn',
                                height: '70px',
                                id: 'okBtnDetail',
                                itemId: 'mybutton18',
                                style: 'float : left; margin-right : 5%',
                                ui: 'action-round',
                                width: '60px',
                                icon: 'assets/icons/okIcon.png',
                                iconCls: 'detailPopUpIcon'
                            },
                            {
                                xtype: 'button',
                                cls: 'generalBtn detailCouponBtn',
                                height: '70px',
                                id: 'deleteBtnDetail',
                                itemId: 'deleteBtnDetail',
                                style: 'float : left;',
                                ui: 'action-round',
                                width: '60px',
                                icon: 'assets/icons/deleteIcon.png',
                                iconCls: 'detailPopUpIcon',
                                text: ''
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onBackDetailBtnCouponTap',
                event: 'tap',
                delegate: '#backDetailBtnCoupon'
            },
            {
                fn: 'onPanelHide',
                event: 'hide'
            },
            {
                fn: 'onPanelUpdatedata',
                event: 'updatedata'
            },
            {
                fn: 'onRedeemBtnDetailTap',
                event: 'tap',
                delegate: '#redeemBtnDetail'
            },
            {
                fn: 'onOkBtnDetailTap',
                event: 'tap',
                delegate: '#okBtnDetail'
            },
            {
                fn: 'onDeleteBtnDetailTap',
                event: 'tap',
                delegate: '#deleteBtnDetail'
            },
            {
                fn: 'onPanelShow',
                event: 'show'
            }
        ]
    },

    onBackDetailBtnCouponTap: function(button, e, options) {
        this.hide();
    },

    onPanelHide: function(component, options) {
        Ext.getBody().un('tap',function(){console.log("sin listener");});

        Ext.getCmp("appContainer").remove(component);

        component.destroy();
    },

    onPanelUpdatedata: function(component, newData, options) {
        var comp = this;

        var appContainer = Ext.getCmp("appContainer");

        Ext.getBody().on('tap',function(e){
            if(e.target.className == "okBtn"){
                this.hide();
            }else if(e.target.className == "delete"){

                var store = Ext.getStore("couponList");

                var record = store.getAt(store.find("couponID",newData.couponID));

                if(record !== undefined){
                    store.remove(record); 
                }

                component.hide();
            }else if(e.target.className === 'redeem' ){

                component.hide();

                MyApp.maskComponent(appContainer,"loading...");

                MyApp.printCoupon(newData.couponID,function(result,printedCoupon){           
                    if(result == 1){                
                        var store = Ext.getStore("couponList");

                        var record = store.getAt(store.find("couponID",newData.couponID));

                        if(record !== undefined){
                            store.remove(record); 
                        }

                        MyApp.unMaskComponent(appContainer);                                

                        Ext.Msg.alert('Added!!', "The coupon has been added to your List of coupons", Ext.emptyFn);

                    }else{

                        MyApp.unMaskComponent(appContainer);

                    }
                });
            }

        },this);
    },

    onRedeemBtnDetailTap: function(button, e, options) {
        var component = this;

        var appContainer = Ext.getCmp("appContainer");

        component.hide();

        MyApp.maskComponent(appContainer,"loading...");

        MyApp.printCoupon(component.getData().couponID,function(result,printedCoupon){           
            if(result == 1){                
                var store = Ext.getStore("couponList");

                var record = store.getAt(store.find("couponID",component.getData().couponID));

                if(record !== undefined){
                    store.remove(record); 
                }

                MyApp.unMaskComponent(appContainer);                                

                //Ext.Msg.alert('Added!!', "The coupon has been added to your List of coupons", Ext.emptyFn);

                if(navigator.notification.alert !== null){

                    navigator.notification.alert('The coupon has been added to your List of coupons',  function(){console.log("ok");},'Added!!','Continue'); 
                }else{
                    alert("The coupon has been added to your List of coupons"); 
                }

            }else{

                MyApp.unMaskComponent(appContainer);

            }
        });
    },

    onOkBtnDetailTap: function(button, e, options) {
        this.hide();
    },

    onDeleteBtnDetailTap: function(button, e, options) {
        console.log("delete clicked " + this.getData().couponID);

        var store = Ext.getStore("couponList");

        var record = store.getAt(store.find("couponID",this.getData().couponID));

        if(record !== undefined){
            store.remove(record); 
        }

        this.hide();
    },

    onPanelShow: function(component, options) {
        var btnContainer = component.getComponent("btnContainer").getComponent("btnContainerRelative");

        if(component.fromAll){    
            btnContainer.getComponent("deleteBtnDetail").hide();
            component.getComponent("btnContainer").setWidth("52%");
        }
    }

});