/*
 * File: app/view/mycoupons.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mycoupons', {
    extend: 'Ext.Panel',
    alias: 'widget.mycoupons',

    config: {
        height: '100%',
        id: 'mycouponsView',
        itemId: 'mycouponsView',
        left: 0,
        top: 0,
        width: '100%',
        layout: {
            type: 'vbox'
        },
        modal: true,
        cls: [
            'generalModal'
        ],
        hideAnimation: {
            type: 'slideOut',
            direction: 'right'
        },
        showAnimation: {
            type: 'slide'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'My Coupons',
                items: [
                    {
                        xtype: 'button',
                        cls: 'generalBtn backBtn',
                        itemId: 'backBtnMyCoupons',
                        ui: 'action-round',
                        icon: 'assets/icons/backIcon.png',
                        iconCls: 'backIcon'
                    }
                ]
            },
            {
                xtype: 'container',
                height: '50px',
                padding: '7px',
                items: [
                    {
                        xtype: 'searchfield',
                        cls: [
                            'customSearchField'
                        ],
                        itemId: 'mysearchfield',
                        width: '100%',
                        inputCls: 'searchInput',
                        placeHolder: 'Search...'
                    }
                ]
            },
            {
                xtype: 'list',
                flex: 1,
                id: 'myCouponList',
                itemId: 'myCouponList',
                itemCls: 'itemList',
                itemTpl: [
                    '<div class=\'itemContainerList\'>',
                    '    <div class=\'imageContainerList\'><img src=\'{image}\'/></div>',
                    '    <p class=\'titleList\'>{name}</p>',
                    '    <p class=\'descriptionList\'>{shortDiscount}...</p>',
                    '</div>    ',
                    '<div class="deleteplaceholder"></div>'
                ],
                store: 'mycouponsStore',
                grouped: true,
                onItemDisclosure: false
            }
        ],
        listeners: [
            {
                fn: 'onBackBtnMyCouponsTap',
                event: 'tap',
                delegate: '#backBtnMyCoupons'
            },
            {
                fn: 'onMysearchfieldKeyup1',
                event: 'keyup',
                delegate: '#mysearchfield'
            },
            {
                fn: 'onMysearchfieldClearicontap1',
                event: 'clearicontap',
                delegate: '#mysearchfield'
            },
            {
                fn: 'onMyCouponListItemTap',
                event: 'itemtap',
                delegate: '#myCouponList'
            },
            {
                fn: 'onMyCouponListItemSwipe',
                event: 'itemswipe',
                delegate: '#myCouponList'
            },
            {
                fn: 'onPanelHide',
                event: 'hide'
            },
            {
                fn: 'onPanelShow',
                event: 'show'
            }
        ]
    },

    onBackBtnMyCouponsTap: function(button, e, options) {
        this.hide();
        MyApp.inAnotherScreen = false;
    },

    onMysearchfieldKeyup1: function(textfield, e, options) {
        //get the store and the value of the field
        var value = textfield.getValue(),
            store = Ext.getStore("mycouponsStore");

        //first clear any current filters on thes tore
        store.clearFilter();

        //check if a value is set first, as if it isnt we dont have to do anything
        if (value) {
            //the user could have entered spaces, so we must split them so we can loop through them all
            var searches = value.split(' '),
                regexps = [],
                i;

            //loop them all
            for (i = 0; i < searches.length; i++) {
                //if it is nothing, continue
                if (!searches[i]) continue;

                //if found, create a new regular expression which is case insenstive
                regexps.push(new RegExp(searches[i], 'i'));
            }

            //now filter the store by passing a method
            //the passed method will be called for each record in the store
            store.filter(function(record) {
                var matched = [];

                //loop through each of the regular expressions
                for (i = 0; i < regexps.length; i++) {
                    var search = regexps[i],
                        didMatch = record.get('name').match(search);

                    //if it matched the first or last name, push it into the matches array
                    matched.push(didMatch);
                }

                //if nothing was found, return false (dont so in the store)
                if (regexps.length > 1 && matched.indexOf(false) != -1) {
                    return false;
                } else {
                    //else true true (show in the store)
                    return matched[0];
                }
            });
        }
    },

    onMysearchfieldClearicontap1: function(text, e, options) {
        //call the clearFilter method on the store instance
        Ext.getStore("mycouponsStore").clearFilter();
    },

    onMyCouponListItemTap: function(dataview, index, target, record, e, options) {
        var elemento = Ext.fly(target).select('#' + target.id + " .deleteBtn");

        var container = Ext.getCmp("appContainer");

        if(e.target.className === 'delete'){
            MyApp.deleteCoupon(record.data.id,function(result){                      

                var store = Ext.getStore("mycouponsStore");

                store.remove(record);                                        

            });
        }

        if(elemento.elements.length === 0){
            var printedDetail = container.getComponent("printedCouponDetail");

            if(printedDetail === undefined){
                console.log("printed no existe");
                printedDetail = Ext.create("MyApp.view.printedCouponDetail");
            }else{
                console.log("printed existe");
                printedDetail.hide();
                container.remove(printedDetail);
                printedDetail.destroy();
                printedDetail = Ext.create("MyApp.view.printedCouponDetail");
            }

            container.add(printedDetail);  

            printedDetail.from = "mycoupons";

            printedDetail.setData(record.data);        

            printedDetail.show();
        }
    },

    onMyCouponListItemSwipe: function(dataview, index, target, record, e, options) {

        var appContainer = Ext.getCmp("appContainer");

        if (e.direction == "left") {

            var del = Ext.create("Ext.Button", {
                ui: "decline",
                text: "Delete",                   
                showAnimation: {type : 'fade'},
                renderTo : Ext.DomQuery.selectNode(".deleteplaceholder", target.dom),        
                cls : 'deleteBtn',
                handler: function() {

                    MyApp.maskComponent(appContainer,"loading...");

                    MyApp.deleteCoupon(record.data.id,function(result){                      

                        MyApp.unMaskComponent(appContainer,"loading...");

                        var store = Ext.getStore("mycouponsStore");

                        store.remove(record);                                        

                    });
                }
            });

            var removeDeleteButton = function() {
                Ext.Anim.run(del, 'fade', {
                    after: function() {
                        del.destroy();
                    },
                    out: true
                });
            };

            del.show();

            dataview.on({
                single: true,
                buffer: 250,
                itemtouchstart: removeDeleteButton
            });
            dataview.element.on({
                single: true,
                buffer: 250,
                touchstart: removeDeleteButton
            });
        }
    },

    onPanelHide: function(component, options) {
        Ext.getCmp("appContainer").remove(component);
        component.destroy();
    },

    onPanelShow: function(component, options) {
        var store = Ext.getStore('mycouponsStore');            

        store.getProxy().setExtraParams({idUsuario : MyApp.userId});                        

        store.load({
            scope : this,
            callback : function(records){        
                console.log("my coupons ok");
            }
        });

    }

});