/*
 * File: app/model/Merchant.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Merchant', {
    extend: 'Ext.data.Model',
    alias: 'model.Merchant',

    uses: [
        'MyApp.model.Coupon'
    ],

    config: {
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'address',
                type: 'string'
            },
            {
                name: 'city',
                type: 'string'
            },
            {
                name: 'state',
                type: 'string'
            },
            {
                name: 'zipCode',
                type: 'string'
            },
            {
                name: 'latitude',
                type: 'string'
            },
            {
                name: 'longitude',
                type: 'string'
            },
            {
                name: 'identificador',
                type: 'string'
            },
            {
                name: 'nuevo',
                type: 'boolean'
            },
            {
                name: 'fechaRegistro',
                type: 'string'
            }
        ],
        hasMany: {
            model: 'MyApp.model.Coupon',
            autoLoad: true,
            foreignKey: 'merchant_id',
            name: 'coupons'
        }
    }
});